language: node_js
node_js:
  - "4.1"
before_install:
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # - export CHROME_BIN=chromium-browser
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
before_script:
  - cd gulp
  - npm install -g karma
  - npm install -g gulp
  - npm install
script: gulp karma-test